RRD-ANTLR4: de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor Class Reference
de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor Class Reference
AST visitor class.
Inherits VoidVisitorAdapter< Object >.
Public Member Functions
void visit (final PackageDeclaration p_package, final Object p_arg)
void visit (final ClassOrInterfaceDeclaration p_class, final Object p_arg)
void visit (final EnumDeclaration p_enum, final Object p_arg)
void visit (final MethodCallExpr p_methodcall, final Object p_arg)
Package Functions
final Set< String > labels ()
returns the translated labels
Private Member Functions
String label (final String p_line)
gets the class name and label name
Static Private Member Functions
static String buildlabel (final String p_package, final String p_outerclass1, final String p_outerclass2, final String p_innerclass, final String p_label)
returns full qualified class name (inner & outer class)
Private Attributes
String m_innerclass = ""
inner class name *
Set< String > m_label = new HashSet<>()
label set
String m_outerclass = ""
outer class name *
String m_package = ""
package name *
Static Private Attributes
static final Pattern LANGUAGEMETHODPATTERN = Pattern.compile(TRANSLATEMETHODNAME + ".+?\\)")
reg expression to extract label data
static final String TRANSLATEMETHODNAME = "CCommon.languagestring"
method to translate strings
Detailed Description
Definition at line 304 of file TestCLanguageLabels.java.
Member Function Documentation
static String de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.buildlabel (final String p_package, final String p_outerclass1, final String p_outerclass2, final String p_innerclass, final String p_label) static private
Parameters
p_package package name
p_outerclass1 outer class readed value
p_outerclass2 outer class fixed value
p_innerclass inner class
p_label label (only firat element is used)
Returns
full-qualified class name
Definition at line 423 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CLASSSEPARATOR.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.label().
String de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.label (final String p_line) private
Parameters
p_line input trimmed line
Returns
label or empty string
Definition at line 390 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.buildlabel(), de.flashpixx.rrd_antlr4.TestCLanguageLabels.CLASSSEPARATOR, de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_innerclass, de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_outerclass, de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_package, de.flashpixx.rrd_antlr4.CCommon.PACKAGEROOT, and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.TRANSLATEMETHODNAME.
final Set<String> de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.labels () package
Returns
set with labels
Definition at line 336 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_label.
void de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit (final PackageDeclaration p_package, final Object p_arg)
Definition at line 342 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_package.
void de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit (final ClassOrInterfaceDeclaration p_class, final Object p_arg)
Definition at line 349 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_innerclass, and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_outerclass.
void de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit (final EnumDeclaration p_enum, final Object p_arg)
Definition at line 362 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_innerclass, and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_outerclass.
void de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit (final MethodCallExpr p_methodcall, final Object p_arg)
Definition at line 375 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_label.
Member Data Documentation
final Pattern de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.LANGUAGEMETHODPATTERN = Pattern.compile(TRANSLATEMETHODNAME + ".+?\\)") static private
Definition at line 313 of file TestCLanguageLabels.java.
String de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_innerclass = "" private
Definition at line 317 of file TestCLanguageLabels.java.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.label(), and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit().
Set<String> de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_label = new HashSet<>() private
Definition at line 329 of file TestCLanguageLabels.java.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.labels(), and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit().
String de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_outerclass = "" private
Definition at line 321 of file TestCLanguageLabels.java.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.label(), and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit().
String de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.m_package = "" private
Definition at line 325 of file TestCLanguageLabels.java.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.label(), and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit().
final String de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.TRANSLATEMETHODNAME = "CCommon.languagestring" static private
Definition at line 309 of file TestCLanguageLabels.java.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.label().